---
name: Test CI

on:
  pull_request:
    paths: [.github/workflows/test_ci.yaml, action.yml]

jobs:
  ci:
    runs-on: ubuntu-24.04

    permissions:
      contents: read # Required to checkout repository.

    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Changed diff-tree
        id: changed
        uses: ./
