---
name: Test CI

on:
  pull_request:
    paths: [.github/workflows/test_ci.yaml, action.yml]

jobs:
  ci:
    runs-on: ubuntu-24.04

    permissions:
      contents: read # Required to checkout repository.

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Changed diff-tree
        id: changed
        uses: ./
